// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZZXZFUszXKjX2pnvX2Z1rbWvnzbdkjzs',
    appId: '1:125629291629:web:133c4ac8b70b718503b364',
    messagingSenderId: '125629291629',
    projectId: 'otrojah-5c407',
    authDomain: 'otrojah-5c407.firebaseapp.com',
    storageBucket: 'otrojah-5c407.appspot.com',
    measurementId: 'G-8DFYGQC2FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6W1myiMC5MiLa0X0_jaieFPuRnX9QNTg',
    appId: '1:125629291629:android:a57dca0ccb9d17e503b364',
    messagingSenderId: '125629291629',
    projectId: 'otrojah-5c407',
    storageBucket: 'otrojah-5c407.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVkdM5-fIh6XCsAmHtNKDzb4FHcB4SdVo',
    appId: '1:125629291629:ios:985490e5e03335ca03b364',
    messagingSenderId: '125629291629',
    projectId: 'otrojah-5c407',
    storageBucket: 'otrojah-5c407.appspot.com',
    iosBundleId: 'com.example.otrojaUsers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVkdM5-fIh6XCsAmHtNKDzb4FHcB4SdVo',
    appId: '1:125629291629:ios:985490e5e03335ca03b364',
    messagingSenderId: '125629291629',
    projectId: 'otrojah-5c407',
    storageBucket: 'otrojah-5c407.appspot.com',
    iosBundleId: 'com.example.otrojaUsers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZZXZFUszXKjX2pnvX2Z1rbWvnzbdkjzs',
    appId: '1:125629291629:web:80d63005d19ec8a503b364',
    messagingSenderId: '125629291629',
    projectId: 'otrojah-5c407',
    authDomain: 'otrojah-5c407.firebaseapp.com',
    storageBucket: 'otrojah-5c407.appspot.com',
    measurementId: 'G-1DRMHP096K',
  );
}
